import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoMigration1787101119042 implements MigrationInterface {
    name = 'AutoMigration1787101119042'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "collections" DROP CONSTRAINT "FK_81f435556d9569d4df980704bce"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6c64b3df09e6774438aeca7e0b"`);
        await queryRunner.query(`CREATE TABLE "genres" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "slug" character varying(120) NOT NULL, "description" text, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f105f8230a83b86a346427de94d" UNIQUE ("name"), CONSTRAINT "UQ_d1cbe4fe39bdfc77c76e94eada5" UNIQUE ("slug"), CONSTRAINT "PK_80ecd718f0f00dde5d77a9be842" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_genres_slug" ON "genres" ("slug") `);
        await queryRunner.query(`CREATE TABLE "cart_items" ("id" SERIAL NOT NULL, "cartId" integer NOT NULL, "bookId" integer NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6fccf5ec03c172d27a28a82928b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_cart_items_cart_book" ON "cart_items" ("cartId", "bookId") `);
        await queryRunner.query(`CREATE TABLE "carts" ("id" SERIAL NOT NULL, "userId" integer, "sessionToken" character varying(255), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_69828a178f152f157dcf2f70a8" UNIQUE ("userId"), CONSTRAINT "PK_b5f695a59f5ebb50af3c8160816" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_addresses" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "alias" character varying(100) NOT NULL, "streetAddress" character varying(200) NOT NULL, "apartmentOrSuite" character varying(100), "city" character varying(100) NOT NULL, "state" character varying(100) NOT NULL, "postalCode" character varying(20) NOT NULL, "country" character varying(100) NOT NULL DEFAULT 'Colombia', "isDefault" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8abbeb5e3239ff7877088ffc25b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" SERIAL NOT NULL, "orderId" integer NOT NULL, "bookId" integer NOT NULL, "quantity" integer NOT NULL, "priceAtPurchase" numeric(12,2) NOT NULL, "totalPrice" numeric(12,2) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('PENDING', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" SERIAL NOT NULL, "orderNumber" character varying(50) NOT NULL, "userId" integer NOT NULL, "status" "public"."orders_status_enum" NOT NULL DEFAULT 'PENDING', "subtotal" numeric(12,2) NOT NULL, "shippingCost" numeric(12,2) NOT NULL DEFAULT '0', "taxAmount" numeric(12,2) NOT NULL DEFAULT '0', "discountAmount" numeric(12,2) NOT NULL DEFAULT '0', "totalAmount" numeric(12,2) NOT NULL, "shippingAddressSnapshot" json NOT NULL, "trackingNumber" character varying(100), "shippingCarrier" character varying(100), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_59b0c3b34ea0fa5562342f24143" UNIQUE ("orderNumber"), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_orders_order_number" ON "orders" ("orderNumber") `);
        await queryRunner.query(`CREATE TABLE "book_reviews" ("id" SERIAL NOT NULL, "bookId" integer NOT NULL, "userId" integer NOT NULL, "rating" smallint NOT NULL, "title" character varying(150), "comment" text, "isApproved" boolean NOT NULL DEFAULT false, "isVerifiedPurchase" boolean NOT NULL DEFAULT false, "helpfulVotes" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cf9cfb9b88fef89b9d747b513d3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_reviews_user_book" ON "book_reviews" ("userId", "bookId") `);
        await queryRunner.query(`CREATE TABLE "wishlist_items" ("id" SERIAL NOT NULL, "wishlistId" integer NOT NULL, "bookId" integer NOT NULL, "addedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0bd52924a97cda208ed2a07bd69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_wishlist_items_wishlist_book" ON "wishlist_items" ("wishlistId", "bookId") `);
        await queryRunner.query(`CREATE TABLE "wishlists" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "name" character varying(100) NOT NULL DEFAULT 'Favoritos', "isMain" boolean NOT NULL DEFAULT true, "isPublic" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d0a37f2848c5d268d315325f359" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" SERIAL NOT NULL, "orderId" integer NOT NULL, "paymentProvider" character varying(50) NOT NULL, "transactionId" character varying(255), "paymentMethod" character varying(50), "amount" numeric(12,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'COP', "status" "public"."payments_status_enum" NOT NULL DEFAULT 'PENDING', "rawResponse" json, "paidAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_payments_provider_transaction" ON "payments" ("transactionId") `);
        await queryRunner.query(`CREATE TYPE "public"."coupons_discounttype_enum" AS ENUM('PERCENTAGE', 'FIXED_AMOUNT')`);
        await queryRunner.query(`CREATE TABLE "coupons" ("id" SERIAL NOT NULL, "code" character varying(50) NOT NULL, "description" text, "discountType" "public"."coupons_discounttype_enum" NOT NULL DEFAULT 'PERCENTAGE', "discountValue" numeric(12,2) NOT NULL, "minPurchaseAmount" numeric(12,2) NOT NULL DEFAULT '0', "maxDiscountAmount" numeric(12,2), "validFrom" TIMESTAMP NOT NULL, "validUntil" TIMESTAMP NOT NULL, "maxUses" integer, "usedCount" integer NOT NULL DEFAULT '0', "maxUsesPerUser" integer NOT NULL DEFAULT '1', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e025109230e82925843f2a14c48" UNIQUE ("code"), CONSTRAINT "PK_d7ea8864a0150183770f3e9a8cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_coupons_code" ON "coupons" ("code") `);
        await queryRunner.query(`CREATE TABLE "author_genres" ("author_id" integer NOT NULL, "genre_id" integer NOT NULL, CONSTRAINT "PK_e9dc42a0faef632b440055175ed" PRIMARY KEY ("author_id", "genre_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_471042f100662031d0eb6f09d2" ON "author_genres" ("author_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_822c510fa31107065b7f760325" ON "author_genres" ("genre_id") `);
        await queryRunner.query(`CREATE TABLE "book_genres" ("book_id" integer NOT NULL, "genre_id" integer NOT NULL, CONSTRAINT "PK_dc2d072b9d76acb4c5f2a4c55e6" PRIMARY KEY ("book_id", "genre_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dc378b8311ff85f0dd38f16309" ON "book_genres" ("book_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_43ff7d87d7506e768ca6491a1d" ON "book_genres" ("genre_id") `);
        await queryRunner.query(`ALTER TABLE "authors" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "authors" DROP COLUMN "literaryGenre"`);
        await queryRunner.query(`ALTER TABLE "publishers" DROP COLUMN "website"`);
        await queryRunner.query(`ALTER TABLE "authors" ADD "firstName" character varying(150) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "authors" ADD "slug" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "authors" ADD CONSTRAINT "UQ_f068a15d416578e89d41189ca25" UNIQUE ("slug")`);
        await queryRunner.query(`ALTER TABLE "authors" ADD "deathdate" date`);
        await queryRunner.query(`ALTER TABLE "authors" ADD "photoUrl" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "publishers" ADD "slug" character varying(180) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "publishers" ADD CONSTRAINT "UQ_680ea69e1be42d33824f592aa70" UNIQUE ("slug")`);
        await queryRunner.query(`ALTER TABLE "publishers" ADD "logoUrl" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "publishers" ADD "websiteUrl" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "collections" ADD "slug" character varying(180) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "collections" ADD CONSTRAINT "UQ_99d0d14f9f23b45d2c6648c4b57" UNIQUE ("slug")`);
        await queryRunner.query(`ALTER TABLE "collections" ADD "coverImageUrl" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "books" ADD "slug" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "books" ADD CONSTRAINT "UQ_4dc5a40933419641440fbd95e8e" UNIQUE ("slug")`);
        await queryRunner.query(`ALTER TABLE "books" ADD "price" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "books" ADD "discountPrice" numeric(10,2)`);
        await queryRunner.query(`CREATE TYPE "public"."books_format_enum" AS ENUM('hardcover', 'paperback', 'ebook', 'audiobook')`);
        await queryRunner.query(`ALTER TABLE "books" ADD "format" "public"."books_format_enum" NOT NULL DEFAULT 'paperback'`);
        await queryRunner.query(`ALTER TABLE "books" ADD "coverImageUrl" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "books" ADD "weightInGrams" integer`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatarUrl" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "isEmailVerified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "authors" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "authors" ADD "lastName" character varying(150)`);
        await queryRunner.query(`ALTER TABLE "authors" DROP COLUMN "birthdate"`);
        await queryRunner.query(`ALTER TABLE "authors" ADD "birthdate" date`);
        await queryRunner.query(`ALTER TABLE "authors" DROP COLUMN "countryOfBirth"`);
        await queryRunner.query(`ALTER TABLE "authors" ADD "countryOfBirth" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "publishers" DROP CONSTRAINT "UQ_39082806f986a63cd7dcf1782a5"`);
        await queryRunner.query(`ALTER TABLE "publishers" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "publishers" ADD "name" character varying(150) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "collections" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "collections" ADD "name" character varying(150) NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."UQ_books_title_author_published_year"`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "books" ADD "title" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "isbn"`);
        await queryRunner.query(`ALTER TABLE "books" ADD "isbn" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "books" ADD CONSTRAINT "UQ_54337dc30d9bb2c3fadebc69094" UNIQUE ("isbn")`);
        await queryRunner.query(`ALTER TABLE "books" ALTER COLUMN "pages" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "books" ALTER COLUMN "publishedYear" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "language"`);
        await queryRunner.query(`ALTER TABLE "books" ADD "language" character varying(10) NOT NULL DEFAULT 'es'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "firstName" character varying(100) NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_authors_slug" ON "authors" ("slug") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_publishers_slug" ON "publishers" ("slug") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_collections_slug" ON "collections" ("slug") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_books_title_author_published_year" ON "books" ("title", "authorId", "publishedYear") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_users_email" ON "users" ("email") `);
        await queryRunner.query(`ALTER TABLE "collections" ADD CONSTRAINT "FK_81f435556d9569d4df980704bce" FOREIGN KEY ("publisherId") REFERENCES "publishers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_edd714311619a5ad09525045838" FOREIGN KEY ("cartId") REFERENCES "carts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_1091797c1c12f2523b1990bd941" FOREIGN KEY ("bookId") REFERENCES "books"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "FK_69828a178f152f157dcf2f70a89" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_addresses" ADD CONSTRAINT "FK_781afdedafe920f331f6229cb62" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_0101724ac3b11e85922928ab86e" FOREIGN KEY ("bookId") REFERENCES "books"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "book_reviews" ADD CONSTRAINT "FK_a7b2ddc7da0f98b88ed04ece7e0" FOREIGN KEY ("bookId") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "book_reviews" ADD CONSTRAINT "FK_9dbdc6bb927296061113eab4447" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wishlist_items" ADD CONSTRAINT "FK_afee7b38d9a4d8e1039e3a0de49" FOREIGN KEY ("wishlistId") REFERENCES "wishlists"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wishlist_items" ADD CONSTRAINT "FK_3a846e75bff6851ab6a51900630" FOREIGN KEY ("bookId") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wishlists" ADD CONSTRAINT "FK_4f3c30555daa6ab0b70a1db772c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_af929a5f2a400fdb6913b4967e1" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "author_genres" ADD CONSTRAINT "FK_471042f100662031d0eb6f09d2d" FOREIGN KEY ("author_id") REFERENCES "authors"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "author_genres" ADD CONSTRAINT "FK_822c510fa31107065b7f7603257" FOREIGN KEY ("genre_id") REFERENCES "genres"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "book_genres" ADD CONSTRAINT "FK_dc378b8311ff85f0dd38f163090" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "book_genres" ADD CONSTRAINT "FK_43ff7d87d7506e768ca6491a1dd" FOREIGN KEY ("genre_id") REFERENCES "genres"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "book_genres" DROP CONSTRAINT "FK_43ff7d87d7506e768ca6491a1dd"`);
        await queryRunner.query(`ALTER TABLE "book_genres" DROP CONSTRAINT "FK_dc378b8311ff85f0dd38f163090"`);
        await queryRunner.query(`ALTER TABLE "author_genres" DROP CONSTRAINT "FK_822c510fa31107065b7f7603257"`);
        await queryRunner.query(`ALTER TABLE "author_genres" DROP CONSTRAINT "FK_471042f100662031d0eb6f09d2d"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_af929a5f2a400fdb6913b4967e1"`);
        await queryRunner.query(`ALTER TABLE "wishlists" DROP CONSTRAINT "FK_4f3c30555daa6ab0b70a1db772c"`);
        await queryRunner.query(`ALTER TABLE "wishlist_items" DROP CONSTRAINT "FK_3a846e75bff6851ab6a51900630"`);
        await queryRunner.query(`ALTER TABLE "wishlist_items" DROP CONSTRAINT "FK_afee7b38d9a4d8e1039e3a0de49"`);
        await queryRunner.query(`ALTER TABLE "book_reviews" DROP CONSTRAINT "FK_9dbdc6bb927296061113eab4447"`);
        await queryRunner.query(`ALTER TABLE "book_reviews" DROP CONSTRAINT "FK_a7b2ddc7da0f98b88ed04ece7e0"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_0101724ac3b11e85922928ab86e"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d"`);
        await queryRunner.query(`ALTER TABLE "user_addresses" DROP CONSTRAINT "FK_781afdedafe920f331f6229cb62"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "FK_69828a178f152f157dcf2f70a89"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_1091797c1c12f2523b1990bd941"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_edd714311619a5ad09525045838"`);
        await queryRunner.query(`ALTER TABLE "collections" DROP CONSTRAINT "FK_81f435556d9569d4df980704bce"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_books_title_author_published_year"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_collections_slug"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_publishers_slug"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_authors_slug"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "firstName" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "language"`);
        await queryRunner.query(`ALTER TABLE "books" ADD "language" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "books" ALTER COLUMN "publishedYear" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "books" ALTER COLUMN "pages" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "books" DROP CONSTRAINT "UQ_54337dc30d9bb2c3fadebc69094"`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "isbn"`);
        await queryRunner.query(`ALTER TABLE "books" ADD "isbn" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "books" ADD "title" character varying NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_books_title_author_published_year" ON "books" ("title", "authorId", "publishedYear") `);
        await queryRunner.query(`ALTER TABLE "collections" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "collections" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "publishers" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "publishers" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "publishers" ADD CONSTRAINT "UQ_39082806f986a63cd7dcf1782a5" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "authors" DROP COLUMN "countryOfBirth"`);
        await queryRunner.query(`ALTER TABLE "authors" ADD "countryOfBirth" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "authors" DROP COLUMN "birthdate"`);
        await queryRunner.query(`ALTER TABLE "authors" ADD "birthdate" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "authors" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "authors" ADD "lastName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "isEmailVerified"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatarUrl"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "weightInGrams"`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "coverImageUrl"`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "format"`);
        await queryRunner.query(`DROP TYPE "public"."books_format_enum"`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "discountPrice"`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "price"`);
        await queryRunner.query(`ALTER TABLE "books" DROP CONSTRAINT "UQ_4dc5a40933419641440fbd95e8e"`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "collections" DROP COLUMN "coverImageUrl"`);
        await queryRunner.query(`ALTER TABLE "collections" DROP CONSTRAINT "UQ_99d0d14f9f23b45d2c6648c4b57"`);
        await queryRunner.query(`ALTER TABLE "collections" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "publishers" DROP COLUMN "websiteUrl"`);
        await queryRunner.query(`ALTER TABLE "publishers" DROP COLUMN "logoUrl"`);
        await queryRunner.query(`ALTER TABLE "publishers" DROP CONSTRAINT "UQ_680ea69e1be42d33824f592aa70"`);
        await queryRunner.query(`ALTER TABLE "publishers" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "authors" DROP COLUMN "photoUrl"`);
        await queryRunner.query(`ALTER TABLE "authors" DROP COLUMN "deathdate"`);
        await queryRunner.query(`ALTER TABLE "authors" DROP CONSTRAINT "UQ_f068a15d416578e89d41189ca25"`);
        await queryRunner.query(`ALTER TABLE "authors" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "authors" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "publishers" ADD "website" character varying`);
        await queryRunner.query(`ALTER TABLE "authors" ADD "literaryGenre" character varying`);
        await queryRunner.query(`ALTER TABLE "authors" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_43ff7d87d7506e768ca6491a1d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc378b8311ff85f0dd38f16309"`);
        await queryRunner.query(`DROP TABLE "book_genres"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_822c510fa31107065b7f760325"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_471042f100662031d0eb6f09d2"`);
        await queryRunner.query(`DROP TABLE "author_genres"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_coupons_code"`);
        await queryRunner.query(`DROP TABLE "coupons"`);
        await queryRunner.query(`DROP TYPE "public"."coupons_discounttype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_payments_provider_transaction"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TABLE "wishlists"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_wishlist_items_wishlist_book"`);
        await queryRunner.query(`DROP TABLE "wishlist_items"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_reviews_user_book"`);
        await queryRunner.query(`DROP TABLE "book_reviews"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_orders_order_number"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP TABLE "user_addresses"`);
        await queryRunner.query(`DROP TABLE "carts"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_cart_items_cart_book"`);
        await queryRunner.query(`DROP TABLE "cart_items"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_genres_slug"`);
        await queryRunner.query(`DROP TABLE "genres"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6c64b3df09e6774438aeca7e0b" ON "authors" ("name") `);
        await queryRunner.query(`ALTER TABLE "collections" ADD CONSTRAINT "FK_81f435556d9569d4df980704bce" FOREIGN KEY ("publisherId") REFERENCES "publishers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
